### ISSUE TITLE
Tarefa 01 - Adicionado página HTML do Stenio

### ISSUE THREAD

**Issue by joeystenio** [tacianosilva/pweb-20205#6]

**Comment by tacianosilva** [comment]
Commits da tarefa: 60afcad

**Comment by tacianosilva** [comment]
@joeystenio para completar a tarefa #6, você deve corrigir o pull request #9. Basta fazer commits no seu fork que o github irá atualizar o PR.

**Comment by tacianosilva** [comment]
@joeystenio fechei essa tarefa. Mas ela ainda precisaria de ajustes.
